"""initial

Revision ID: 08704cab3ae5
Revises: 
Create Date: 2026-06-21 19:50:29.377120
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08704cab3ae5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_hospital',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='医院主键'),
    sa.Column('hospital_name', sa.String(length=50), nullable=False, comment='医院名称'),
    sa.Column('hospital_level', sa.String(length=20), nullable=True, comment='医院等级'),
    sa.Column('address', sa.String(length=200), nullable=True, comment='医院地址'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Integer(), server_default='0', nullable=False, comment='0未删除 1已删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('wx_openid', sa.String(length=128), nullable=True, comment='模拟微信唯一标识'),
    sa.Column('username', sa.String(length=32), nullable=True, comment='登录账号'),
    sa.Column('password', sa.String(length=64), nullable=False, comment='bcrypt加密登录密码'),
    sa.Column('nickname', sa.String(length=64), nullable=False, comment='用户昵称'),
    sa.Column('user_type', sa.Integer(), nullable=False, comment='1老年用户 2子女用户 3管理员'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Integer(), server_default='0', nullable=False, comment='0未删除 1已删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('wx_openid')
    )
    op.create_table('tb_volunteer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='志愿者主键'),
    sa.Column('vol_name', sa.String(length=32), nullable=False, comment='志愿者姓名'),
    sa.Column('vol_phone', sa.String(length=20), nullable=False, comment='联系电话'),
    sa.Column('service_dept', sa.String(length=100), nullable=True, comment='可服务科室'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='志愿者头像地址'),
    sa.Column('service_desc', sa.String(length=255), nullable=True, comment='陪诊服务简介、从业经验'),
    sa.Column('service_score', sa.Numeric(precision=2, scale=1), nullable=False, comment='综合服务评分1-5分'),
    sa.Column('service_count', sa.Integer(), nullable=False, comment='累计完成陪诊次数'),
    sa.Column('status', sa.Integer(), nullable=False, comment='1可预约 0不可预约'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Integer(), server_default='0', nullable=False, comment='0未删除 1已删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_department',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.BigInteger(), nullable=False, comment='所属医院ID'),
    sa.Column('dept_name', sa.String(length=50), nullable=False, comment='科室名称'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Integer(), server_default='0', nullable=False, comment='0未删除 1已删除'),
    sa.ForeignKeyConstraint(['hospital_id'], ['tb_hospital.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_elder_bind',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('child_uid', sa.BigInteger(), nullable=False, comment='子女用户ID'),
    sa.Column('elder_name', sa.String(length=32), nullable=False, comment='长辈姓名'),
    sa.Column('elder_id_card', sa.String(length=20), nullable=True, comment='长辈身份证号'),
    sa.Column('elder_phone', sa.String(length=20), nullable=True, comment='长辈联系电话'),
    sa.Column('gender', sa.Integer(), nullable=False, comment='1男 2女'),
    sa.Column('birthday', sa.Date(), nullable=True, comment='长辈出生日期，用于自动核算年龄'),
    sa.Column('medical_card', sa.String(length=50), nullable=False, comment='医保卡编号'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Integer(), server_default='0', nullable=False, comment='0未删除 1已删除'),
    sa.ForeignKeyConstraint(['child_uid'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='消息主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='接收用户ID'),
    sa.Column('msg_type', sa.Integer(), nullable=False, comment='1系统通知 2挂号通知 3候诊通知 4健康提醒 5陪诊通知'),
    sa.Column('msg_content', sa.String(length=255), nullable=False, comment='消息内容'),
    sa.Column('read_status', sa.Integer(), nullable=False, comment='0未读 1已读'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Integer(), server_default='0', nullable=False, comment='0未删除 1已删除'),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_accompany_order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='陪诊订单主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='下单子女用户ID'),
    sa.Column('elder_bind_id', sa.BigInteger(), nullable=False, comment='陪同长辈ID'),
    sa.Column('volunteer_id', sa.BigInteger(), nullable=False, comment='用户自主选定志愿者ID'),
    sa.Column('accompany_date', sa.Date(), nullable=False, comment='陪诊日期'),
    sa.Column('order_status', sa.Integer(), nullable=False, comment='1待审核 2待服务 3服务中 4已完成 5已取消'),
    sa.Column('service_score', sa.Integer(), nullable=True, comment='用户评价打分1-5分'),
    sa.Column('service_comment', sa.String(length=200), nullable=True, comment='陪诊文字评价'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Integer(), server_default='0', nullable=False, comment='0未删除 1已删除'),
    sa.ForeignKeyConstraint(['elder_bind_id'], ['tb_elder_bind.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['tb_volunteer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_doctor',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dept_id', sa.BigInteger(), nullable=False, comment='所属科室ID'),
    sa.Column('doctor_name', sa.String(length=32), nullable=False, comment='医生姓名'),
    sa.Column('doctor_title', sa.String(length=20), nullable=True, comment='医生职称'),
    sa.Column('specialty', sa.String(length=200), nullable=True, comment='擅长诊疗病症'),
    sa.Column('register_fee', sa.Numeric(precision=8, scale=2), nullable=False, comment='单次挂号资费'),
    sa.Column('doctor_avatar', sa.String(length=255), nullable=True, comment='医生头像存储地址'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Integer(), server_default='0', nullable=False, comment='0未删除 1已删除'),
    sa.ForeignKeyConstraint(['dept_id'], ['tb_department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_health_reminder',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('remind_type', sa.String(length=20), nullable=False, comment='medicine/revisit/checkup'),
    sa.Column('remind_time', sa.String(length=5), nullable=False, comment='HH:MM'),
    sa.Column('remind_content', sa.String(length=255), nullable=False, comment='提醒内容'),
    sa.Column('elder_bind_id', sa.BigInteger(), nullable=True, comment='长辈ID'),
    sa.Column('repeat_days', sa.Integer(), nullable=False, comment='重复间隔天数 0=不重复'),
    sa.Column('is_active', sa.Integer(), nullable=False, comment='1启用 0停用'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Integer(), server_default='0', nullable=False, comment='0未删除 1已删除'),
    sa.ForeignKeyConstraint(['elder_bind_id'], ['tb_elder_bind.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_physical_report',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('elder_bind_id', sa.BigInteger(), nullable=False, comment='绑定长辈ID'),
    sa.Column('report_url', sa.String(length=255), nullable=False, comment='报告图片地址'),
    sa.Column('ocr_result', sa.Text(), nullable=True, comment='OCR识别原始结果JSON'),
    sa.Column('interpretation', sa.Text(), nullable=True, comment='通俗化解读文本'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Integer(), server_default='0', nullable=False, comment='0未删除 1已删除'),
    sa.ForeignKeyConstraint(['elder_bind_id'], ['tb_elder_bind.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_schedule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.BigInteger(), nullable=False, comment='医生ID'),
    sa.Column('work_date', sa.Date(), nullable=False, comment='出诊日期'),
    sa.Column('time_period', sa.String(length=10), nullable=False, comment='AM上午 PM下午 ALL全天'),
    sa.Column('normal_num', sa.Integer(), nullable=False, comment='普通号数量'),
    sa.Column('elder_priority_num', sa.Integer(), nullable=False, comment='老年优先号'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Integer(), server_default='0', nullable=False, comment='0未删除 1已删除'),
    sa.ForeignKeyConstraint(['doctor_id'], ['tb_doctor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_reserve',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='预约用户'),
    sa.Column('schedule_id', sa.BigInteger(), nullable=False, comment='排班ID'),
    sa.Column('elder_bind_id', sa.BigInteger(), nullable=True, comment='代办长辈ID'),
    sa.Column('source_type', sa.String(length=10), nullable=False, comment='号源类型：normal普通 / elder老年优先'),
    sa.Column('queue_code', sa.String(length=20), nullable=True, comment='候诊排队编号'),
    sa.Column('queue_status', sa.Integer(), nullable=False, comment='候诊状态：1等待中 2就诊中 3已完成'),
    sa.Column('pay_status', sa.Integer(), nullable=False, comment='1待支付 2已支付 3超时取消'),
    sa.Column('order_status', sa.Integer(), nullable=False, comment='订单状态：1待支付 2已预约 3已就诊 4已取消'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Integer(), server_default='0', nullable=False, comment='0未删除 1已删除'),
    sa.ForeignKeyConstraint(['elder_bind_id'], ['tb_elder_bind.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['tb_schedule.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_pay_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reserve_id', sa.BigInteger(), nullable=False, comment='关联预约单ID'),
    sa.Column('pay_money', sa.Numeric(precision=10, scale=2), nullable=False, comment='缴费金额'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Integer(), server_default='0', nullable=False, comment='0未删除 1已删除'),
    sa.ForeignKeyConstraint(['reserve_id'], ['tb_reserve.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_pay_record')
    op.drop_table('tb_reserve')
    op.drop_table('tb_schedule')
    op.drop_table('tb_physical_report')
    op.drop_table('tb_health_reminder')
    op.drop_table('tb_doctor')
    op.drop_table('tb_accompany_order')
    op.drop_table('tb_message')
    op.drop_table('tb_elder_bind')
    op.drop_table('tb_department')
    op.drop_table('tb_volunteer')
    op.drop_table('tb_user')
    op.drop_table('tb_hospital')
    # ### end Alembic commands ###
