"""add_alipay_fields_to_pay_record

Revision ID: 29202f402497
Revises: a1b2c3d4e5f6
Create Date: 2026-06-23 10:03:48.416941
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '29202f402497'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_pay_record', sa.Column('trade_no', sa.String(length=64), nullable=False, comment='支付宝交易号'))
    op.add_column('tb_pay_record', sa.Column('out_trade_no', sa.String(length=64), nullable=False, comment='商户订单号'))
    op.add_column('tb_pay_record', sa.Column('pay_channel', sa.String(length=20), nullable=False, comment='支付渠道：alipay / mock'))
    op.add_column('tb_pay_record', sa.Column('pay_status', sa.Integer(), nullable=False, comment='支付状态：1待支付 2已支付 3已关闭'))
    op.alter_column('tb_pay_record', 'id',
               existing_type=mysql.BIGINT(),
               comment='缴费记录ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tb_pay_record', 'reserve_id',
               existing_type=mysql.BIGINT(),
               comment='预约订单ID',
               existing_comment='关联预约单ID',
               existing_nullable=False)
    op.create_index(op.f('ix_tb_pay_record_out_trade_no'), 'tb_pay_record', ['out_trade_no'], unique=False)
    op.create_index(op.f('ix_tb_pay_record_reserve_id'), 'tb_pay_record', ['reserve_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_pay_record_reserve_id'), table_name='tb_pay_record')
    op.drop_index(op.f('ix_tb_pay_record_out_trade_no'), table_name='tb_pay_record')
    op.alter_column('tb_pay_record', 'reserve_id',
               existing_type=mysql.BIGINT(),
               comment='关联预约单ID',
               existing_comment='预约订单ID',
               existing_nullable=False)
    op.alter_column('tb_pay_record', 'id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='缴费记录ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('tb_pay_record', 'pay_status')
    op.drop_column('tb_pay_record', 'pay_channel')
    op.drop_column('tb_pay_record', 'out_trade_no')
    op.drop_column('tb_pay_record', 'trade_no')
    # ### end Alembic commands ###
