"""make_medical_card_nullable

Revision ID: a8c54db0eff6
Revises: 08704cab3ae5
Create Date: 2026-06-22 02:22:18.274472
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a8c54db0eff6'
down_revision: Union[str, None] = '08704cab3ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_elder_bind', 'medical_card',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True,
               existing_comment='医保卡编号')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_elder_bind', 'medical_card',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False,
               existing_comment='医保卡编号')
    # ### end Alembic commands ###
